/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    screens: {
      sm: "480px",
      sam:"580px",
      md: "768px",
      lg: "976px",
      xl: "1440px",
      nd: "1020px",
    },
    colors: {
      blue: "#1fb6ff",
      purple: "#7e5bef",
      pink: "#ff49db",
      orange: "#ff7849",
      green: "#13ce66",
      yellow: "#ffc82c",
      "gray-dark": "#273444",
      gray: "#8492a6",
      "gray-light": "#d3dce6",
      "black-light": "#191619",
      white: "#ffffff",
      "magenta-light": "#FF9D98",
      "border-color": "#393939",
      "text-color": "#DFDFDF",
      "header-bg-color": "#101213",
      black: "#000000",
      "todo-card": "#CAECCC",
      "todo-text-color": "#FF9D98",
      "todo-text-inactive": "#DFDFDF",
      "todo-card-one": "#EBDCFE",
      "todo-card-two": "#B3DFF6",
      "todo-card-three": "#FCEDBE",
      "todo-card-four": "#F8BEBE",
      "modal-dark" : "#212121",
      "modal-light" : "#393939",
      "modal-input-text" : "#828282",
      "save-button-color" : "#FF9D98",
      "border-light-color" : "#333333"
    },
    fontFamily: {
      sans: ["Graphik", "sans-serif"],
      serif: ["Merriweather", "serif"],
      dm: ["DM Sans"],
    },
    fontSize: {
      sm: "0.8rem",
      base: "1rem",
      xl: "1.25rem",
      "2xl": "1.563rem",
      "3xl": "1.953rem",
      "4xl": "2.441rem",
      "5xl": "3.052rem",
    },
    extend: {
      spacing: {
        128: "32rem",
        144: "36rem",
        724: "724px",
        452: "452px",
        44: "44px",
        50: "50px",
        665: "665px",
        550: "550px",
      },
      borderRadius: {
        "4xl": "2rem",
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
